/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockFArrakisV2 } from "./MockFArrakisV2";
export type { MockFArrakisV2Factory } from "./MockFArrakisV2Factory";
