/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface MockFArrakisV2FactoryInterface extends Interface {
  getFunction(nameOrSignature: "append" | "getTokenOrder"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "append",
    values: [string, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenOrder",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "append", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTokenOrder",
    data: BytesLike
  ): Result;
}

export interface MockFArrakisV2Factory extends BaseContract {
  connect(runner?: ContractRunner | null): MockFArrakisV2Factory;
  waitForDeployment(): Promise<this>;

  interface: MockFArrakisV2FactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  append: TypedContractMethod<
    [a_: string, b_: string, c_: string, d_: string],
    [string],
    "view"
  >;

  getTokenOrder: TypedContractMethod<
    [tokenA_: AddressLike, tokenB_: AddressLike],
    [[string, string] & { token0: string; token1: string }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "append"
  ): TypedContractMethod<
    [a_: string, b_: string, c_: string, d_: string],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenOrder"
  ): TypedContractMethod<
    [tokenA_: AddressLike, tokenB_: AddressLike],
    [[string, string] & { token0: string; token1: string }],
    "view"
  >;

  filters: {};
}
