/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type RangeStruct = {
  lowerTick: BigNumberish;
  upperTick: BigNumberish;
  feeTier: BigNumberish;
};

export type RangeStructOutput = [
  lowerTick: bigint,
  upperTick: bigint,
  feeTier: bigint
] & { lowerTick: bigint; upperTick: bigint; feeTier: bigint };

export type RangeWeightStruct = { range: RangeStruct; weight: BigNumberish };

export type RangeWeightStructOutput = [
  range: RangeStructOutput,
  weight: bigint
] & { range: RangeStructOutput; weight: bigint };

export type PositionLiquidityStruct = {
  liquidity: BigNumberish;
  range: RangeStruct;
};

export type PositionLiquidityStructOutput = [
  liquidity: bigint,
  range: RangeStructOutput
] & { liquidity: bigint; range: RangeStructOutput };

export type SwapPayloadStruct = {
  payload: BytesLike;
  router: AddressLike;
  amountIn: BigNumberish;
  expectedMinReturn: BigNumberish;
  zeroForOne: boolean;
};

export type SwapPayloadStructOutput = [
  payload: string,
  router: string,
  amountIn: bigint,
  expectedMinReturn: bigint,
  zeroForOne: boolean
] & {
  payload: string;
  router: string;
  amountIn: bigint;
  expectedMinReturn: bigint;
  zeroForOne: boolean;
};

export type RebalanceStruct = {
  burns: PositionLiquidityStruct[];
  mints: PositionLiquidityStruct[];
  swap: SwapPayloadStruct;
  minBurn0: BigNumberish;
  minBurn1: BigNumberish;
  minDeposit0: BigNumberish;
  minDeposit1: BigNumberish;
};

export type RebalanceStructOutput = [
  burns: PositionLiquidityStructOutput[],
  mints: PositionLiquidityStructOutput[],
  swap: SwapPayloadStructOutput,
  minBurn0: bigint,
  minBurn1: bigint,
  minDeposit0: bigint,
  minDeposit1: bigint
] & {
  burns: PositionLiquidityStructOutput[];
  mints: PositionLiquidityStructOutput[];
  swap: SwapPayloadStructOutput;
  minBurn0: bigint;
  minBurn1: bigint;
  minDeposit0: bigint;
  minDeposit1: bigint;
};

export interface IArrakisV2ResolverInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAmountsForLiquidity"
      | "getMintAmounts"
      | "getPositionId"
      | "standardRebalance"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getAmountsForLiquidity",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMintAmounts",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPositionId",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "standardRebalance",
    values: [RangeWeightStruct[], AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAmountsForLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMintAmounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPositionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "standardRebalance",
    data: BytesLike
  ): Result;
}

export interface IArrakisV2Resolver extends BaseContract {
  connect(runner?: ContractRunner | null): IArrakisV2Resolver;
  waitForDeployment(): Promise<this>;

  interface: IArrakisV2ResolverInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAmountsForLiquidity: TypedContractMethod<
    [
      sqrtPriceX96_: BigNumberish,
      lowerTick_: BigNumberish,
      upperTick_: BigNumberish,
      liquidity_: BigNumberish
    ],
    [[bigint, bigint] & { amount0: bigint; amount1: bigint }],
    "view"
  >;

  getMintAmounts: TypedContractMethod<
    [
      vaultV2_: AddressLike,
      amount0Max_: BigNumberish,
      amount1Max_: BigNumberish
    ],
    [
      [bigint, bigint, bigint] & {
        amount0: bigint;
        amount1: bigint;
        mintAmount: bigint;
      }
    ],
    "view"
  >;

  getPositionId: TypedContractMethod<
    [addr_: AddressLike, lowerTick_: BigNumberish, upperTick_: BigNumberish],
    [string],
    "view"
  >;

  standardRebalance: TypedContractMethod<
    [rangeWeights_: RangeWeightStruct[], vaultV2_: AddressLike],
    [RebalanceStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAmountsForLiquidity"
  ): TypedContractMethod<
    [
      sqrtPriceX96_: BigNumberish,
      lowerTick_: BigNumberish,
      upperTick_: BigNumberish,
      liquidity_: BigNumberish
    ],
    [[bigint, bigint] & { amount0: bigint; amount1: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMintAmounts"
  ): TypedContractMethod<
    [
      vaultV2_: AddressLike,
      amount0Max_: BigNumberish,
      amount1Max_: BigNumberish
    ],
    [
      [bigint, bigint, bigint] & {
        amount0: bigint;
        amount1: bigint;
        mintAmount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPositionId"
  ): TypedContractMethod<
    [addr_: AddressLike, lowerTick_: BigNumberish, upperTick_: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "standardRebalance"
  ): TypedContractMethod<
    [rangeWeights_: RangeWeightStruct[], vaultV2_: AddressLike],
    [RebalanceStructOutput],
    "view"
  >;

  filters: {};
}
