/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockFArrakisV2__factory } from "./MockFArrakisV2__factory";
export { MockFArrakisV2Factory__factory } from "./MockFArrakisV2Factory__factory";
