/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type { Pool, PoolInterface } from "../../../contracts/libraries/Pool";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "pool_",
        type: "address",
      },
      {
        components: [
          {
            internalType: "int24",
            name: "lowerTick",
            type: "int24",
          },
          {
            internalType: "int24",
            name: "upperTick",
            type: "int24",
          },
          {
            internalType: "uint24",
            name: "feeTier",
            type: "uint24",
          },
        ],
        internalType: "struct Range",
        name: "range_",
        type: "tuple",
      },
    ],
    name: "validateTickSpacing",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x61028961003a600b82828239805160001a60731461002d57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600436106100355760003560e01c80636b0188201461003a575b600080fd5b61004d610048366004610135565b610061565b604051901515815260200160405180910390f35b6000808373ffffffffffffffffffffffffffffffffffffffff1663d0c93a7c6040518163ffffffff1660e01b8152600401602060405180830381865afa1580156100af573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906100d391906101ff565b9050826020015160020b836000015160020b1280156100ff575082516100fa908290610223565b60020b155b801561011b57508083602001516101169190610223565b60020b155b949350505050565b8060020b811461013257600080fd5b50565b600080828403608081121561014957600080fd5b833573ffffffffffffffffffffffffffffffffffffffff8116811461016d57600080fd5b92506060601f198201121561018157600080fd5b506040516060810181811067ffffffffffffffff821117156101b357634e487b7160e01b600052604160045260246000fd5b60405260208401356101c481610123565b815260408401356101d481610123565b6020820152606084013562ffffff811681146101ef57600080fd5b6040820152919491935090915050565b60006020828403121561021157600080fd5b815161021c81610123565b9392505050565b60008260020b8061024457634e487b7160e01b600052601260045260246000fd5b808360020b079150509291505056fea26469706673582212208300321020beae77b2447b122c3bb19d6d02410d8e35c67b96a77952ccce717964736f6c634300080d0033";

type PoolConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PoolConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Pool__factory extends ContractFactory {
  constructor(...args: PoolConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Pool & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Pool__factory {
    return super.connect(runner) as Pool__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PoolInterface {
    return new Interface(_abi) as PoolInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Pool {
    return new Contract(address, _abi, runner) as unknown as Pool;
  }
}
