/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IArrakisV2Beacon,
  IArrakisV2BeaconInterface,
} from "../../../contracts/interfaces/IArrakisV2Beacon";

const _abi = [
  {
    inputs: [],
    name: "implementation",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newImplementation",
        type: "address",
      },
    ],
    name: "upgradeTo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IArrakisV2Beacon__factory {
  static readonly abi = _abi;
  static createInterface(): IArrakisV2BeaconInterface {
    return new Interface(_abi) as IArrakisV2BeaconInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IArrakisV2Beacon {
    return new Contract(address, _abi, runner) as unknown as IArrakisV2Beacon;
  }
}
